### PR TITLE
Fix UncommunicativeVariableName does not take regex configuration into account.

### LINKED ISSUE #1063: UncommunicativeVariableName does not take regex configuration into account
Found this bug while investigating #1058 

Given this config.reek:

```yaml
---
UncommunicativeVariableName:
  accept:
  - /\d+$/
```

this:

```Ruby
def foo; x1 = 2; end
```

shouldn't smell of UncommunicativeVariableName.
Unfortunately it does:

```
 reek -c config.reek foo.rb
foo.rb -- 1 warning:
  [1]:UncommunicativeVariableName: foo has the variable name 'x1'
```

The reason for this behaviour is [here](https://github.com/troessner/reek/blob/master/lib/reek/smells/uncommunicative_variable_name.rb#L66):

```Ruby
      def bad_name?(name, _ctx)
        var = name.to_s.gsub(/^[@\*\&]*/, '')
        return false if accept_names.include?(var) # <- here is the problem!
        reject_names.find { |patt| patt =~ var }
      end
```

We only check for literals here, not for regexes. 
The other Uncommunicative* smell detectors are **not** affected by the issue since they rightfully check for literals and regexes.

### PR DESCRIPTION
**Pull request by troessner**
Fixes #1063

### CODE REVIEW

File: lib/reek/smells/uncommunicative_variable_name.rb [hunk 1]
```diff
@@ -24,7 +24,7 @@ class UncommunicativeVariableName < SmellDetector
       # The name of the config field that lists the regexps of
       # smelly names to be reported.
       REJECT_KEY = 'reject'.freeze
-      DEFAULT_REJECT_SET = [/^.$/, /[0-9]$/, /[A-Z]/].freeze
+      DEFAULT_REJECT_SET = [/^[a-z]$/, /[0-9]$/].freeze
```
Comment (troessner) [inline lib/reek/smells/uncommunicative_variable_name.rb]: This /[A-Z]/ would have never ended up here (since it would have been parsed differently) and this /^.$/ was a bug already in my mind. Should have been /[a-z]/ from the beginning.

File: lib/reek/smells/uncommunicative_variable_name.rb [hunk 2]
```diff
@@ -61,10 +62,15 @@ def sniff(ctx)
...
-        var = name.to_s.gsub(/^[@\*\&]*/, '')
-        return false if accept_names.include?(var)
-        reject_names.find { |patt| patt =~ var }
+      private
+
+      def uncommunicative_variable_name?(name)
+        !acceptable_name?(name)
+      end
+
+      def acceptable_name?(name)
```
Comment (troessner) [inline lib/reek/smells/uncommunicative_variable_name.rb]: I know this seems unnecessary. The method body from here could go into `uncommunicative_variable_name` directly. But I find positive predicate method names easier to read and it's easier to build up a mental image of them.

File: lib/reek/smells/uncommunicative_variable_name.rb [hunk 3]
```diff
@@ -124,8 +130,6 @@ def record_variable_name(exp, symbol, accumulator)
         accumulator[var].push(exp.line)
       end
 
-      private
```
Comment (troessner) [inline lib/reek/smells/uncommunicative_variable_name.rb]: All methods of this detector were public before :-/

File: lib/reek/smells/uncommunicative_variable_name.rb (hunk 1 above)
Comment (mvz) [inline lib/reek/smells/uncommunicative_variable_name.rb]: I think `/[A-Z]/` is meant to catch stuff like `aVariable`.

File: lib/reek/smells/uncommunicative_variable_name.rb [hunk 4]
```diff
@@ -61,10 +62,15 @@ def sniff(ctx)
...
-        return false if accept_names.include?(var)
-        reject_names.find { |patt| patt =~ var }
+      private
+
+      def uncommunicative_variable_name?(name)
+        !acceptable_name?(name)
+      end
+
+      def acceptable_name?(name)
+        Array(accept_names).any? { |accept_pattern| name.match accept_pattern } ||
```
Comment (troessner) [inline lib/reek/smells/uncommunicative_variable_name.rb]: This is now **almost** the same as we do in all other Uncommunicative* detectors with the exception of the "Array()" call (which we need if the user gives us literal values). 
I intend to remove the "Array()" call again when I tackle #1066

**Comment by troessner** [comment]
Ready for review!

File: lib/reek/smells/uncommunicative_variable_name.rb (hunk 1 above)
Comment (troessner) [inline lib/reek/smells/uncommunicative_variable_name.rb]: A yes! I'll add a spec (nothing broke on removal) and reintroduce it.

**Comment by troessner** [comment]
Addressed all comments and added a spec for camelcasing! LGTM? :)

File: lib/reek/smells/uncommunicative_variable_name.rb [hunk 5]
```diff
@@ -24,13 +26,17 @@ class UncommunicativeVariableName < SmellDetector
...
+        /[0-9]$/,  # any name ending with a number
+        /[A-Z]/    # camelCaseVariableNames
+      ].freeze
 
       # The name of the config field that lists the specific names that are
       # to be treated as exceptions; these names will not be reported as
       # uncommunicative.
       ACCEPT_KEY = 'accept'.freeze
-      DEFAULT_ACCEPT_SET = ['_'].freeze
+      DEFAULT_ACCEPT_SET = [/^_/].freeze
```
Comment (mvz) [inline lib/reek/smells/uncommunicative_variable_name.rb]: This makes us accept `_aBadName42`. I think the original intent was to accept `_` as the only valid single-character name.

File: lib/reek/smells/uncommunicative_variable_name.rb [hunk 6]
```diff
@@ -24,13 +26,17 @@ class UncommunicativeVariableName < SmellDetector
       # The name of the config field that lists the regexps of
       # smelly names to be reported.
       REJECT_KEY = 'reject'.freeze
-      DEFAULT_REJECT_SET = [/^.$/, /[0-9]$/, /[A-Z]/].freeze
+      DEFAULT_REJECT_SET = [
+        /^[a-z]$/, # single-character names
```
Comment (mvz) [inline lib/reek/smells/uncommunicative_variable_name.rb]: Since Ruby allows loads of unicode characters in variable names, I think this is too narrow. This detector will now happily accept the variable name `é`.

**Comment by troessner** [comment]
@mvz addressed all your comments! LGTM? :)
