### PR TITLE
Fix `accept` and `reject` configuration handling.

### LINKED ISSUE #886: UncommunicativeParameterName claims to allow `accept: /<regex>/`, doesn't
according to https://github.com/troessner/reek/blob/master/docs/Uncommunicative-Parameter-Name.md#configuration, the UncommunicativeParameterName smell should allow a specification like:

```yaml
UncommunicativeParameterName:
  accept: /^[a|b]$/
```

unfortunately, when i do that (OSX, ruby 2.0.0p481, reek-3.11), i get an error:
```
reek -c .reek ./**/*.rb
/Users/conor/.rvm/gems/ruby-2.0.0-p481/gems/reek-3.11/lib/reek/smells/uncommunicative_parameter_name.rb:64:in 
`acceptable_name?': undefined method `any?' for "/^[a|b]$/":String (NoMethodError)
```

since i just added some UncommunicativeVariableName expectations in the same way, i was a bit confused. 

i assumed that these two smells would be implemented similarly, but they are not. 

there are 2 problems as i see it:
  * the return coming out of `accept_names(context)` is not iterable, so `any?` cannot be used
  * https://github.com/troessner/reek/blob/master/lib/reek/smells/uncommunicative_parameter_name.rb#L61 explicitly calls out `accept_names` and `reject_patterns`, and then uses `==` and `match` for comparison

until i send a PR/someone else fixes this, i'm working around this problem by specifying my UncommunicativeParameterName configuration as:
```yaml
UncommunicativeParameterName:
  accept:
    - a
    - b
```

### PR DESCRIPTION
**Pull request by troessner**
Preliminary PR, fixes #886, successor of #887 (which had a bad branch name in the end)
What does this bad boy do?
Glad you asked!

* consistent handling of `reject` and `accept`
* makes both settings handle strings and regexes properly
* makes both settings handle list and single values
* tests!
* Updates and improves our documentation

Tomorrow I'll make some final tweaks and then this is ready for review!

### CODE REVIEW

**Comment by troessner** [comment]
Ladies and gentlemen, this little rascal is ready for review!
+353 −35 
I know it's scary but most of the additions are missing tests ;)

**Comment by troessner** [comment]
Well, well, well. Mutant fails :laughing: 
I'll add specs but this thing is still reviewable.

File: lib/reek/smells/uncommunicative_method_name.rb [hunk 1]
```diff
@@ -49,17 +50,17 @@ def inspect(context)
 
       private
 
-      def acceptable_name?(name:, context:)
-        accept_names(context).any? { |accept_name| name == accept_name } ||
-          reject_patterns(context).none? { |pattern| name.match pattern }
+      def acceptable_pattern?(name:, context:)
```
Comment (mvz) [inline lib/reek/smells/uncommunicative_method_name.rb]: I would keep the name `acceptable_name?`, since that's what you're checking.

`accept_patterns` etc. are all good name-wise.

**Comment by mvz** [comment]
Looks good, just one small nit.

Do you want to move these methods into a module, or do you want to move straight to implementing #889?

I was going to comment on only having cucumber scenarios for this change, but mutant did it for me :smile:.

File: lib/reek/smells/uncommunicative_method_name.rb (hunk 1 above)
Comment (troessner) [inline lib/reek/smells/uncommunicative_method_name.rb]: Good point, fixed in all 3 affected smell detectors.

**Comment by mvz** [comment]
Regarding the mutant output, I'm wondering about this one:

```
-  super.merge(REJECT_KEY => DEFAULT_REJECT_PATTERNS, ACCEPT_KEY => DEFAULT_ACCEPT_PATTERNS)
+  super().merge(REJECT_KEY => DEFAULT_REJECT_PATTERNS, ACCEPT_KEY => DEFAULT_ACCEPT_PATTERNS)
```

For a method without any parameters, this is not really a meaningful change. I suppose we'll see if it remains once the other items have been taken care of.

**Comment by troessner** [comment]
Well, well, well. To quote the current youth: FML. That looks like I need to add a gazillion specs to make this pass not to mention that I need to refactor the specs for all 3 detectors because at the moment the look like crap.

-> wip, pls stand by.

**Comment by troessner** [comment]
Ready for final review!

mutant is still red, but never mind. I improved cucumber and spec coverage for the `accept` and `reject` feature by roughly 5000%. If you check out the PR you'll see that it adds hundreds of lines of test coverage to something that was literally untested before.

I feel that this is more than enough.

Let's get this merged asap.
