### PR TITLE
Fetch a module's name from the source

### LINKED ISSUE #832: undefined method `full_name' for s(:lvar, :m):#<Class:0x00>
Code to reproduce

```ruby
m = Module.new

module m::N
end
```

Commit which I think introduced the regression: 8bf26f9dea4ed16e3282bbf9d4ed1dc98af21133

### PR DESCRIPTION
**Pull request by mvz**
Fixes #832.

### CODE REVIEW

File: spec/reek/ast/sexp_extensions_spec.rb [hunk 1]
```diff
@@ -342,7 +341,7 @@
 
   context 'with a scoped name' do
     subject do
-      sexp(:module, sexp(:const, sexp(:const, nil, :Foo), :Bar), nil)
+      Reek::Source::SourceCode.from('module Foo::Bar; end').syntax_tree
```
Comment (troessner) [inline spec/reek/ast/sexp_extensions_spec.rb]: We should have a helper for that, but we can add this another time.
