### PR TITLE
Improve documentation and fix PrimaDonnaMethod detector configuration via comment.

### LINKED ISSUE #903: Can't suppress PrimaDonnaMethod and UnusedPrivateMethod smells in method context
I have this code:

```
class Bang
  # :reek:PrimaDonnaMethod
  def bang_one!
    puts "bang!"
  end
  def bang_two!
    puts "bang bang!!"
  end
end
```

Reek still report 2 PrimaDonnaMethod smells.
I know that PrimaDonnaMethod and UnusedPrivateMethod work in class context. But it makes me can't suppress the warning partially. Is it actually intended to be like that?

### PR DESCRIPTION
**Pull request by troessner**
Fixes #903

### CODE REVIEW

**Comment by troessner** [comment]
Ready for review!

**Comment by troessner** [comment]
@mvz are you for a review?

**Comment by mvz** [comment]
@troessner I'm going to make some time for reviews over the weekend.

File: lib/reek/smell_detectors/prima_donna_method.rb [hunk 1]
```diff
@@ -28,9 +28,27 @@ def self.contexts # :nodoc:
...
+      #
+      # s(:class,
+      #   s(:const, nil, :Alfa), nil,
+      #     s(:def, :bravo!,
+      #       s(:args), nil))
+      #
       def sniff(ctx)
         ctx.node_instance_methods.select do |method_sexp|
-          prima_donna_method?(method_sexp, ctx)
+          prima_donna_method?(method_sexp, ctx) && !ignore_method?(method_sexp, ctx)
```
Comment (mvz) [inline lib/reek/smell_detectors/prima_donna_method.rb]: I think swapping these will make things faster.

File: lib/reek/smell_detectors/prima_donna_method.rb [hunk 2]
```diff
@@ -55,6 +73,20 @@ def version_without_bang_exists?(method_sexp, ctx)
...
+
+      #
+      # @param method_node [Reek::AST::Node],
+      #   e.g. s(:def, :bravo!, s(:args), nil)
+      # @param ctx [Context::ModuleContext]
+      # @return [Boolean]
+      #
+      def ignore_method?(method_node, ctx)
+        ignore_method_names = value(EXCLUDE_KEY, ctx) # e.g. ["bravo!"]
+        ignore_method_names.any? do |ignore_method_name|
```
Comment (mvz) [inline lib/reek/smell_detectors/prima_donna_method.rb]: How about `ignore_method_names.include? method_node.name.to_s`?

File: lib/reek/smell_detectors/prima_donna_method.rb (hunk 1 above)
Comment (mvz) [inline lib/reek/smell_detectors/prima_donna_method.rb]: Actually, the best option may be to have the `ignore_method?` check between `method_sexp.ends_with_bang?` and `version_without_bang_exists?(method_sexp, ctx)`.

File: features/command_line_interface/options.feature [hunk 3]
```diff
@@ -41,7 +41,9 @@ Feature: Reek can be controlled using command-line options
 
       Configuration:
           -c, --config FILE                Read configuration options from FILE
-              --smell SMELL                Detect smell SMELL (default: all enabled smells)
+              --smell SMELL                Only look for a specific smell.
+                                           Call it like this: reek --smell PrimaDonnaMethod source.rb
+                                           Check out https://github.com/troessner/reek/blob/master/docs/Code-Smells.md for a list of smells
```
Comment (troessner) [inline features/command_line_interface/options.feature]: Why? It is helpful, isn't it? And it's not like the output for our help flag is a wall of text already.
In doubt, I would **always** pick the option that is more helpful for the user.

**Comment by troessner** [comment]
Addressed all of your comments @mvz :)

File: features/command_line_interface/options.feature (hunk 3 above)
Comment (Drenmi) [inline features/command_line_interface/options.feature]: > https://github.com/troessner/reek/blob/master/docs/Code-Smells.md for a list of smells

Is there a command to list all smells? That would save me from having to leave the terminal, and tread into the dangerous realm of distractions that live in the browser. 😅

Comment (troessner) [inline features/command_line_interface/options.feature]: @Drenmi there isn't, but I agree, sth like "reek --list" would be awesome and actually almost trivial to implement. Care for a PR? ;)

Comment (Drenmi) [inline features/command_line_interface/options.feature]: @troessner: Maybe we start with an issue, because there are some questions that will likely crop up, like what and how much to print, and whether it needs to be reconsidered as the list of smells grows. 😀

Comment (troessner) [inline features/command_line_interface/options.feature]: Sure, feel free to create an issue so we can discuss this further there :)

**Comment by troessner** [comment]
Lgtm @mvz ?

**Comment by mvz** [comment]
Sure, why not 😄.
