### PR TITLE
Make Reek more resilient on incomprehensible source.

### LINKED ISSUE #995: Make Reek more resilient on incomprehensible source.
Coming from #942 and #953 we agreed on the following:

We have smell detectors sometimes failing for unexpected reasons, and Reek aborts.
In order to be able to drill down to the root of this problem we decided to:

* Print a (detailed) error
* and skip that source.

so that the user can open up a bug report with enough information for us to fix it.

### PR DESCRIPTION
**Pull request by troessner**
Fixes #995, heavily wip.

### CODE REVIEW

**Comment by troessner** [comment]
This one is depending on #997

**Comment by mvz** [comment]
#997 has been merged, so this can be rebased I think.

**Comment by troessner** [comment]
Ready for review!

**Comment by mvz** [comment]
I'll have a look tomorrow.

File: spec/reek/examiner_spec.rb [hunk 1]
```diff
@@ -108,5 +108,42 @@
         expect(examiner.smells).to eq([])
       end
     end
+
+    context 'with an incomprehensible source that causes Reek to crash' do
+      let(:subject) do
+        examiner = described_class.new 'class C; def does_crash_reek; end; end'
+        allow(examiner).to receive(:smell_repository) do
```
Comment (mvz) [inline spec/reek/examiner_spec.rb]: I'm don't like it if the object under test is stubbed. Can we avoid this by either injecting `SmellRepository`, or stubbing `SmellRepository.new` directly?

File: spec/reek/examiner_spec.rb [hunk 2]
```diff
@@ -108,5 +108,42 @@
         expect(examiner.smells).to eq([])
       end
     end
+
+    context 'with an incomprehensible source that causes Reek to crash' do
+      let(:subject) do
```
Comment (mvz) [inline spec/reek/examiner_spec.rb]: Can you replace this with either `subject do ...`, or (preferred) `let(:examiner) do`?

File: spec/spec_helper.rb [hunk 3]
```diff
@@ -3,6 +3,7 @@
 require_relative '../lib/reek/spec'
 require_relative '../lib/reek/ast/ast_node_class_map'
 require_relative '../lib/reek/configuration/app_configuration'
+require 'active_support/core_ext/string/strip'
```
Comment (mvz) [inline spec/spec_helper.rb]: Why did you move this?

**Comment by mvz** [comment]
Just a few nits, then it's ready to go.

File: spec/reek/examiner_spec.rb (hunk 1 above)
Comment (troessner) [inline spec/reek/examiner_spec.rb]: >> Can we avoid this by either injecting SmellRepository

I'd prefer that as well but our current Examiner constructor signature is not supporting so we'd have to add this. Which would mean that it would take 4 arguments, which I find quite a lot but still manageable. Are you suggesting to update the Examiner constructor to be like this:

```Ruby

    def initialize(source,
                   filter_by_smells: [],
                   configuration: Configuration::AppConfiguration.default,
                   smell_repository: Smells::SmellRepository.new)
end
```

?

>> or stubbing SmellRepository.new directly?

I can't see the benefit. For me this would be even worse since it is more opaque - you're stubbing something that is not even called directly thus making it harder to build up a mental image. Why do you think this is better?

File: spec/reek/examiner_spec.rb (hunk 2 above)
Comment (troessner) [inline spec/reek/examiner_spec.rb]: Good point, fixed!

File: spec/spec_helper.rb (hunk 3 above)
Comment (troessner) [inline spec/spec_helper.rb]: The overall rationale here was that we use `strip_heredoc` in multiple places so it would make sense to require this in the spec_helper.
But you're right, this really doesn't belong to this PR, I just undid this change.

File: spec/reek/examiner_spec.rb (hunk 1 above)
Comment (mvz) [inline spec/reek/examiner_spec.rb]: > Are you suggesting to update the Examiner constructor to be like this:

We probably need to inject the class instead of an instance, but yes, something like that.

> > or stubbing SmellRepository.new directly?
> I can't see the benefit. For me this would be even worse since it is more opaque - you're stubbing something that is not even called directly thus making it harder to build up a mental image. Why do you think this is better?

I think `SmellRepository.new` is actually called directly in `Examiner`. But to answer more broadly, I have found again and again that stubbing the object under test is really the most dangerous option, since it tends to hide bugs in the implementation of the object itself.

File: lib/reek/examiner.rb [hunk 4]
```diff
@@ -12,6 +12,19 @@ module Reek
   #
   # :reek:TooManyInstanceVariables: { max_instance_variables: 7 }
   class Examiner
+    INCOMPREHENSIBLE_SOURCE_TEMPLATE = <<-EOS.freeze
+      !!!
+      Source %s can not be processed by Reek.
+      This is most likely a Reek bug.
+      It would be great if you could report this back to the Reek team
+      by opening up a corresponding issue at https://github.com/troessner/reek/issues
+      Make sure to include the source in question, the Reek version
```
Comment (Drenmi) [inline lib/reek/examiner.rb]: Just a thought. Would it be feasible to have all this information ready to be copied and pasted from the error message, rather than having the user go and gather it?

Comment (troessner) [inline lib/reek/examiner.rb]: Awesome idea!
I'll add this, thanks!

File: spec/reek/examiner_spec.rb [hunk 5]
```diff
@@ -108,5 +108,42 @@
         expect(examiner.smells).to eq([])
       end
     end
+
+    context 'with an incomprehensible source that causes Reek to crash' do
+      subject do
+        examiner = described_class.new 'class C; def does_crash_reek; end; end'
+        allow(examiner).to receive(:smell_repository) do
```
Comment (mvz) [inline spec/reek/examiner_spec.rb]: (comment copied so it is not hidden)

> Are you suggesting to update the Examiner constructor to be like this:

We probably need to inject the class instead of an instance, but yes, something like that.

> >  or stubbing SmellRepository.new directly?

>  I can't see the benefit. For me this would be even worse since it is more opaque - you're stubbing something that is not even called directly thus making it harder to build up a mental image. Why do you think this is better?

I think SmellRepository.new is actually called directly in Examiner. But to answer more broadly, I have found again and again that stubbing the object under test is really the most dangerous option, since it tends to hide bugs in the implementation of the object itself.

**Comment by troessner** [comment]
@mvz addressed of all your feedback in 2 separate commits, the first one making SmellRepository injectable and the second one making the specs less brittle.

I'll address 

>> Would it be feasible to have all this information ready to be copied and pasted from the error message, rather than having the user go and gather it?

in a separate pull request to not block this one (see #1019)

LGTM?

**Comment by mvz** [comment]
It looks like you're not using the new dependency injection possibility in the specs?

**Comment by troessner** [comment]
>> It looks like you're not using the new dependency injection possibility in the specs?

Exactly! I started out with adding it but when it came to the spec itself I realized that RSpec's awesome 

```Ruby
class_double('Reek::Smells::SmellRepository').as_stubbed_const
```

works as well for this very spec. I still left the DI in there because a) I think we should start using DI way more in our codebase and b) starting to DI SmellRepository might be useful for subsequent specs. That's why it's 2 separate commits.

I can also remove the DI for SmellRepository but I think it makes sense to keep it for above reasons.

WDYT?

**Comment by mvz** [comment]
Ok, clear.
