### PR TITLE
Fix smell_details handling in `reek_of` matcher.

### LINKED ISSUE #599: Fix reek_of matcher messages
The failure messages for `reek_of` are too general. For example, if the match fails due to the details being wrong, it just says it didn't smell.

### PR DESCRIPTION
**Pull request by troessner**
Fixes #599 
Actually this feature (properly checking and reacting to missing smell_details) was never implemented ;)

### CODE REVIEW

File: spec/reek/spec/should_reek_of_spec.rb [hunk 1]
```diff
@@ -3,61 +3,113 @@
 require_relative '../../../lib/reek/spec'
 
 RSpec.describe Reek::Spec::ShouldReekOf do
-  context 'rdoc demo example' do
-    let(:ruby) { 'def double_thing() @other.thing.foo + @other.thing.foo end' }
+  describe 'smell type check' do
```
Comment (troessner) [inline spec/reek/spec/should_reek_of_spec.rb]: I refactored the whole file so the diff is a little messy I'm afraid. Probably better if you check the whole file when reviewing, not the diff.

File: lib/reek/spec/should_reek_of.rb [hunk 2]
```diff
@@ -17,22 +23,42 @@ def initialize(smell_category,
 
       def matches?(actual)
         self.examiner = Examiner.new(actual, configuration: configuration)
-        self.all_smells = examiner.smells
-        all_smells.any? { |warning| warning.matches?(smell_category, smell_details) }
+
+        set_failure_messages_for_smell_type && return unless matching_smell_types?
+        set_failure_messages_for_smell_details && return unless matching_smell_details?
+
+        true
```
Comment (chastell) [inline lib/reek/spec/should_reek_of.rb]: After looking at it for some time I finally understood the logic behind this (two sets of messages, we set one for one failure, the other for the other failure and none + return `true` if there are no failures), but I still think it reads sub-optimally.

How about being a bit more verbose, but explicit:

```ruby
def matches?(actual)
  self.examiner = Examiner.new(actual, configuration: configuration)
  set_failure_messages
  matching_smell_types? && matching_smell_details?
end

private

def set_failure_messages
  set_failure_messages_for_smell_details unless matching_smell_details?
  set_failure_messages_for_smell_type unless matching_smell_types?
end
```

**Comment by chastell** [comment]
One nitpick that kept me stumped every time I started reviewing this one and then LGTM. :)

File: lib/reek/spec/should_reek_of.rb (hunk 2 above)
Comment (troessner) [inline lib/reek/spec/should_reek_of.rb]: But the code you suggest is even more confusing, at least for me:

```Ruby
def set_failure_messages
  set_failure_messages_for_smell_details unless matching_smell_details?
  set_failure_messages_for_smell_type unless matching_smell_types?
end
```

This code gives the impression that both validations are independent from each other. But they are not. The second one is dependent on the first one because it can't stand on it's own.

With my implementation at least this is clear because I say "&& return". With your suggestion, it is (quoting a famous man) "baroque" ;)

Comment (troessner) [inline lib/reek/spec/should_reek_of.rb]: But the code you suggest is even more confusing, at least for me:

```Ruby
def set_failure_messages
  set_failure_messages_for_smell_details unless matching_smell_details?
  set_failure_messages_for_smell_type unless matching_smell_types?
end
```

This code gives the impression that both validations are independent from each other. But they are not. The second one is dependent on the first one because it can't stand on it's own.

With my implementation at least this is clear because I say "&& return". With your suggestion, it is (quoting a famous man) "baroque" ;)

Comment (chastell) [inline lib/reek/spec/should_reek_of.rb]: > This code gives the impression that both validations are independent from each other. But they are not. The second one is dependent on the first one because it can't stand on it's own.

Oh ok, this is a very good point. My initial proposition (which I refactored to the above) was the below `case` – maybe this is a good compromise between readability, the right mechanics and clearer `#matches?` return values?

```ruby
def matches?(actual)
  self.examiner = Examiner.new(actual, configuration: configuration)
  case
  when not matching_smell_types?
    set_failure_messages_for_smell_type
    false
  when not matching_smell_details?
    set_failure_messages_for_smell_details
    false
  else
    true
  end
end
```

(This all stems from `#matches?` doing two distinct things – setting the failure messages and returning a proper boolean. The above at least makes it clear what’s going on when.)

Comment (chastell) [inline lib/reek/spec/should_reek_of.rb]: Alternatively split the responsibilities:

```ruby
def matches?(actual)
  self.examiner = Examiner.new(actual, configuration: configuration)
  case
  when not matching_smell_types?
    set_failure_messages_for_smell_type
  when not matching_smell_details?
    set_failure_messages_for_smell_details
  end
  matching_smell_types? && matching_smell_details?
end
```

(Not sure if clearer.)

Comment (troessner) [inline lib/reek/spec/should_reek_of.rb]: But none of your suggestions above deal with:

````This code gives the impression that both validations are independent from each other. But they are not. The matching_smell_details? one is dependent on the matching_smell_types? one because it can't stand on it's own.````

Which is why I still believe that my initial solution is better.

How about a compromise with something like this:

```Ruby
def matches?(actual)
  if matching_smell_types?
    if matching_smell_details?
      return true
    else
      set_failure_messages_for_smell_details
    end
  else
    set_failure_messages_for_smell_types
  end
  false
end
```

WDYT?

Comment (chastell) [inline lib/reek/spec/should_reek_of.rb]: OK, I see how the `case` does not show the strict dependency – but the two `&& return unless` lines didn’t either. :)

The clearest to me would probably be

```ruby
case
when matching_smell_types? and matching_smell_details?
  true
when matching_smell_types? and not matching_smell_details?
  set_failure_messages_for_smell_details
  false
when not matching_smell_types?
  set_failure_messages_for_smell_types
  false
end
```

…but I’m also OK with your `if`-`if`-`else`-`else` proposal.

Comment (troessner) [inline lib/reek/spec/should_reek_of.rb]: >> …but I’m also OK with your if-if-else-else proposal.

Updated!

**Comment by troessner** [comment]
Addressed all comments - merge? ;)

**Comment by troessner** [comment]
Alright guys, I believe this pull request has been really discussed and changed long enough.

Can somebody merge this now please or are there bigger concerns left?

**Comment by troessner** [comment]
Squashed and ready!

**Comment by mvz** [comment]
Oh, GitHub, where did my comments go? :cry:
