### PR TITLE
Check casgn value responds to type

### LINKED ISSUE #622: Reek fails on use of ||= with constants
I ran into an issue with the use of the or equals operator on constants.

Example file (test.rb):
```ruby
module Foo
  FOO ||= :foo
end
```

Output of ```reek test.rb```:
```
$ reek test.rb
/Library/Ruby/Gems/2.0.0/gems/reek-3.1/lib/reek/ast/sexp_extensions.rb:408:in `defines_module?': undefined method `type' for :FOO:Symbol (NoMethodError)
	from /Library/Ruby/Gems/2.0.0/gems/reek-3.1/lib/reek/tree_walker.rb:54:in `process_casgn'
	from /Library/Ruby/Gems/2.0.0/gems/reek-3.1/lib/reek/tree_walker.rb:38:in `process'
	from /Library/Ruby/Gems/2.0.0/gems/reek-3.1/lib/reek/tree_walker.rb:77:in `block in process_default'
	from /Library/Ruby/Gems/2.0.0/gems/reek-3.1/lib/reek/tree_walker.rb:76:in `each'
	from /Library/Ruby/Gems/2.0.0/gems/reek-3.1/lib/reek/tree_walker.rb:76:in `process_default'
	from /Library/Ruby/Gems/2.0.0/gems/reek-3.1/lib/reek/tree_walker.rb:40:in `process'
	from /Library/Ruby/Gems/2.0.0/gems/reek-3.1/lib/reek/tree_walker.rb:77:in `block in process_default'
	from /Library/Ruby/Gems/2.0.0/gems/reek-3.1/lib/reek/tree_walker.rb:76:in `each'
	from /Library/Ruby/Gems/2.0.0/gems/reek-3.1/lib/reek/tree_walker.rb:76:in `process_default'
	from /Library/Ruby/Gems/2.0.0/gems/reek-3.1/lib/reek/tree_walker.rb:47:in `block in process_module'
	from /Library/Ruby/Gems/2.0.0/gems/reek-3.1/lib/reek/tree_walker.rb:191:in `block in inside_new_context'
	from /Library/Ruby/Gems/2.0.0/gems/reek-3.1/lib/reek/tree_walker.rb:199:in `push'
	from /Library/Ruby/Gems/2.0.0/gems/reek-3.1/lib/reek/tree_walker.rb:190:in `inside_new_context'
	from /Library/Ruby/Gems/2.0.0/gems/reek-3.1/lib/reek/tree_walker.rb:46:in `process_module'
	from /Library/Ruby/Gems/2.0.0/gems/reek-3.1/lib/reek/tree_walker.rb:38:in `process'
	from /Library/Ruby/Gems/2.0.0/gems/reek-3.1/lib/reek/tree_walker.rb:27:in `walk'
	from /Library/Ruby/Gems/2.0.0/gems/reek-3.1/lib/reek/examiner.rb:73:in `run'
	from /Library/Ruby/Gems/2.0.0/gems/reek-3.1/lib/reek/examiner.rb:35:in `initialize'
	from /Library/Ruby/Gems/2.0.0/gems/reek-3.1/lib/reek/cli/reek_command.rb:14:in `new'
	from /Library/Ruby/Gems/2.0.0/gems/reek-3.1/lib/reek/cli/reek_command.rb:14:in `block in execute'
	from /Library/Ruby/Gems/2.0.0/gems/reek-3.1/lib/reek/cli/reek_command.rb:13:in `each'
	from /Library/Ruby/Gems/2.0.0/gems/reek-3.1/lib/reek/cli/reek_command.rb:13:in `execute'
	from /Library/Ruby/Gems/2.0.0/gems/reek-3.1/lib/reek/cli/application.rb:34:in `execute'
	from /Library/Ruby/Gems/2.0.0/gems/reek-3.1/bin/reek:11:in `<top (required)>'
	from /usr/bin/reek:23:in `load'
	from /usr/bin/reek:23:in `<main>'
```

### PR DESCRIPTION
**Pull request by HParker**
Seems that the issue is `casgn`'s value did not respond to type when `tree_walker` is trying to decide if it `defines_module?`

since it doesn't respond to type, I think it is safe to say that it does not define a module.

### CODE REVIEW

**Comment by mvz** [comment]
Fixes #622

File: lib/reek/ast/sexp_extensions.rb [hunk 1]
```diff
@@ -405,6 +405,7 @@ module CasgnNode
         MODULE_DEFINERS = [:Class, :Struct]
 
         def defines_module?
+          return false unless value.respond_to?(:type)
```
Comment (mvz) [inline lib/reek/ast/sexp_extensions.rb]: I would prefer to avoid `respond_to?`.

My educated guess is that, given the sexp used in the test, we would expect value to be `nil`, whereas actually, it is `:Foo`. I.e., the `:casgn` sexp has the following structure:

```
s(:casgn, <namespace>, <name>, <value>)
```

If the value is empty, parser does not include it. Due to the naïve implementation of `#value`, it then returns the name instead.

So IMHO a better solution is to fix `#value` and make `defines_module?` return false if `value` is `nil`.

**Comment by mvz** [comment]
Hi @HParker thanks for your pull request. Please take a look at my comment on the diff.

**Comment by HParker** [comment]
@mvz if you wouldn't mind taking a look at https://github.com/troessner/reek/commit/18d8074a2833af5f33b444f30cae5198600d50ac I think you are right this is a much better implementation.

File: lib/reek/ast/sexp_extensions.rb [hunk 2]
```diff
@@ -421,7 +422,7 @@ def name
         end
 
         def value
-          children.last
+          children.last if children.size > 2
```
Comment (troessner) [inline lib/reek/ast/sexp_extensions.rb]: Can you please add an explanatory comment that shows an example for the S-exp?

Comment (HParker) [inline lib/reek/ast/sexp_extensions.rb]: @troessner how would you feel about a comment something like,

```Ruby
# there are two valid forms of the casgn sexp
# (casgn <namespace> <name> <value>) and
# (casgn <namespace> <name>) used in or-asgn and mlhs
```

Here are a couple examples,
```
source = "class Hi; THIS, THAT = 2, 5; end"
Reek::Source::SourceCode.from(source).syntax_tree
(class
 (const nil :Hi) nil
 (masgn
  (mlhs
   (casgn nil :THIS)
   (casgn nil :THAT))
  (array
   (int 2)
   (int 5))))
```

```
source = "class Hi; THIS ||= 3; end"
(class
 (const nil :Hi) nil
 (or-asgn
  (casgn nil :THIS)
  (int 3)))
```

Comment (troessner) [inline lib/reek/ast/sexp_extensions.rb]: The last example would be picture-perfect in my mind.:)

Comment (mvz) [inline lib/reek/ast/sexp_extensions.rb]: Or you can go with `children[2]` and avoid a lot of complication :smile:.

:+1: on adding the explanation and example.

**Comment by HParker** [comment]
Incorporated feedback. Hope the comment structure works for you all.
Let me know if I need to squish commits or anything before merge.

**Comment by troessner** [comment]
Could you please add a unit test that actually ensures that we can now parse

```Ruby
module Foo
  Bar ||= :hossa
end 
```

properly? Then this would be good to go from my side.:)

**Comment by HParker** [comment]
Would that be in tree_walker_spec? I am having trouble finding a good place for it. Sorry, still learning the structure of the code.

**Comment by troessner** [comment]
>> Would that be in tree_walker_spec? 

Yes, it would.:)

**Comment by mvz** [comment]
Or alternatively, in irresponsible_module_spec.

**Comment by HParker** [comment]
added two specs that mirror the use cases referenced in the issue.

**Comment by troessner** [comment]
Looking good! Just one last thing, could you please squash it to one commit?
Then we can merge this :)

**Comment by HParker** [comment]
oh god what did I do. Hold on.

**Comment by HParker** [comment]
apparently 5 years of git is not enough to know how to interactive rebase. Sorry for the spam. I am going to try to start fresh here.

**Comment by HParker** [comment]
well, I learned some important lessons today. Thankfully I learned them on a small change. Sorry again for the noise. Hopefully everything is good now.

**Comment by troessner** [comment]
>> Hopefully everything is good now.

It is! Restarting the build for rubinius to make travis happy.....as soon as it's green I'll merge.;)

**Comment by troessner** [comment]
Merged, thanks a lot for this @HParker !

Releasing a new version right away to bring this fix live.
