### PR TITLE
Do not hide exceptions in reek_of matcher

### LINKED ISSUE #1027: Handle or fail tests when smell detectors return nil
When `#sniff` returns `nil` instead of `[]`, our tests still pass but we output our please-report-an-exception text. We should either allow `nil` output or fail tests in this case.

I found this with mutant when implementing #1026.

### PR DESCRIPTION
**Pull request by mvz**
Fixes #1027.

An alternative is to make Examiner not catch exceptions, but introduce a SafeExaminer that does and use that from the CLI.

### CODE REVIEW

**Comment by mvz** [comment]
I'm not entirely happy with this implementation: We make Examiner and SmellRepository jump through hoops to match only one smell, plus the replacement of Examiner with UnsafeExaminer is hard to test.

I'm going to try some refactoring.

**Comment by troessner** [comment]
Great, then I can hold off with my review ;)

**Comment by mvz** [comment]
Dammit, I can't make the change easy. There's just too much coming together in Examiner.

**Comment by mvz** [comment]
@troessner please review as-is. Also, wdyt about the other option? A third option is moving the exception handling up into the Reporter class.

**Comment by troessner** [comment]
Will review both this one and #1041 tomorrow :)

**Comment by troessner** [comment]
"Was du heute kannst besorgen, das verschiebe nicht auf morgen" as we say in Germany.

Which roughly translates to "F*ck it, I'm reviewing now"

File: lib/reek/smells/smell_repository.rb [hunk 1]
```diff
@@ -25,6 +25,7 @@ def self.smell_types
       # @return [Array<Reek::Smells::SmellDetector>] All SmellDetectors that we want to filter for
       #         e.g. [Reek::Smells::Attribute].
       def self.eligible_smell_types(filter_by_smells = [])
+        filter_by_smells = Array(filter_by_smells)
```
Comment (troessner) [inline lib/reek/smells/smell_repository.rb]: Hmmm. Hmmm. Well. It seems like you're trying to make up for Ruby's lack of static typing.
If you're doing this here, shouldn't we then consequently update ALL methods in Reek?
This change seems arbitrary - Why do we do this?

File: lib/reek/spec.rb [hunk 2]
```diff
@@ -38,8 +38,8 @@ module Reek
   # To check for specific smells, use something like this:
   #
   #   ruby = 'def double_thing() @other.thing.foo + @other.thing.foo end'
-  #   ruby.should reek_of(:Duplication, /@other.thing[^\.]/)
-  #   ruby.should reek_of(:Duplication, /@other.thing.foo/)
+  #   ruby.should reek_of(:DuplicateMethodCall, name: '@other.thing')
+  #   ruby.should reek_of(:DuplicateMethodCall, name: '@other.thing.foo', count: 2)
```
Comment (troessner) [inline lib/reek/spec.rb]: Good catch!

File: lib/reek/spec/should_reek_of.rb [hunk 3]
```diff
@@ -9,20 +9,30 @@ module Spec
     # code smell.
     #
     class ShouldReekOf
+      # Variant of Examiner that doesn't swallow exceptions
+      class UnsafeExaminer < Examiner
+        def run
+          examine source.syntax_tree
+          smell_repository.report_on(collector)
```
Comment (troessner) [inline lib/reek/spec/should_reek_of.rb]: This will break with #1041 merged - we probably should get #1041 merged first and then update this one.

**Comment by troessner** [comment]
Reviewed, looks good overall!

File: lib/reek/smells/smell_repository.rb (hunk 1 above)
Comment (mvz) [inline lib/reek/smells/smell_repository.rb]: I do this to ensure we have an array, so the `#include?` later on uses the Array version, rather than the String version. This stops mutant from suggesting removal of quite a bit of code elsewhere. However, this is a bit of a leftover from an earlier direction I took in implementing this, and it can go now.

File: lib/reek/spec/should_reek_of.rb (hunk 3 above)
Comment (mvz) [inline lib/reek/spec/should_reek_of.rb]: Yeah either way I will need to rewrite this bit in one of the PRs.

File: lib/reek/smells/smell_repository.rb (hunk 1 above)
Comment (troessner) [inline lib/reek/smells/smell_repository.rb]: >> I do this to ensure we have an array, so the #include? later on uses the Array version, rather than the String version. 

Ok, maybe I should phrased that better :)
My question was of provocative nature. I understand why you're doing this but it feels erratic. Here we would do this but there are another 100 places in our code where we're not doing this. 
I'd prefer to remove it.

Comment (mvz) [inline lib/reek/smells/smell_repository.rb]: Yes, I'll remove it. It is unfortunate that Ruby's String and Array methods often have the same names.

**Comment by mvz** [comment]
Rebased and updated.
