### PR TITLE
Fail properly on bad configuration comments.

### LINKED ISSUE #1069: Problems with the way we handle CodeComments
I see 2 huge problems at the moment:

1.) Something like

>>
      # :reek:DuplicateMethodCall: { wtf is this!? }

is a **valid** expression looking at our [comment regex](https://github.com/troessner/reek/blob/master/lib/reek/code_comment.rb#L10)

2.) The comment above will lead to a Runtime error like this:

```
[3] pry(#<Reek::CodeComment>)> c
      !!!
      Source lib/reek/ast/node.rb can not be processed by Reek.
      This is most likely a Reek bug.
      It would be great if you could report this back to the Reek team
      by opening up a corresponding issue at https://github.com/troessner/reek/issues
      Make sure to include the source in question, the Reek version
      and the original exception below.

      Original exception:
      #<Psych::SyntaxError: (<unknown>): did not find expected ',' or '}' while parsing a flow mapping at line 1 column 22>
      !!!
```

Obviously this is a catastrophe from a users perspective. Nobody will get this.
This behaviour is a consequence of #996 which we completely missed when discussing the pull request  👎 

I suggest the following:

* make the comment regex more robust
* do NOT catch errors that emerge from configuration handling in our smell detectors but let them bubble up analogous to #1039 
* post-process those kind of exceptions in a way that makes them more meaningful for the users.

WDYT?

### PR DESCRIPTION
**Pull request by troessner**
Fixes #1069 - heavily wip.

### CODE REVIEW

**Comment by troessner** [comment]
Hmmm, I'm a little stuck with this one. The problem is that when I put the validation into CodeComments initializer then the error message gets reported multiple times - once for every context.
E.g. this innocent example:

```Ruby
# :reek:UnknownSmellDetector
def x
end
```

would cause the same output on stderr twice because the code sample would be parsed into a RootContext that contains a MethodContext.

Off the top of my head I can think of 3 possible solutions:

1.) We kind of check what context it makes sense to output something. RootContext is probably something that should never write anything on stderr. But that feels very hacky and again our overall design.
2.) Do the validation in `TreeDresser.new.dress`. That would work well I believe. But then we have the problem that the comment creation and validation are done in different places. Pretty uncool. 
3.) We kind of buffer everything we want to write to stderr somewhere, somehow and then only write the unique elements of this buffer to stderr at the very end.

I'm kind of leaning towards [3] but I'd love to hear your ideas about this @mvz && @waldyr  ;)

**Comment by troessner** [comment]
Come to think about this, such a buffering mechanism might come in handy for all kinds of things. We could basically buffer all-the-things to stderr including our error handling in the Examiner.
And then, at the very end, we could put out one concise summary.

**Comment by mvz** [comment]
I'm leaning towards just aborting the examination of that file at the first error and printing a more specific message in our exception handler.

File: lib/reek/code_comment.rb [hunk 1]
```diff
@@ -20,19 +21,42 @@ class CodeComment
...
+    # @param source [String] - Path to source file or "string"
     #
-    def initialize(comment)
+    def initialize(comment:, line:, source:)
       @original_comment  = comment
       @config            = Hash.new { |hash, key| hash[key] = {} }
 
       @original_comment.scan(CONFIGURATION_REGEX) do |detector, _option_string, options|
+        unless Smells::SmellDetector.valid_detector?(detector)
+          $stderr.puts format(UNKNOWN_SMELL_DETECTOR_MESSAGE,
```
Comment (mvz) [inline lib/reek/code_comment.rb]: Ah I see what your approach is. Rather than having output to `$stderr` all over the place, let's just raise a custom exception here that we catch further up the call stack.

File: lib/reek/code_comment.rb [hunk 2]
```diff
@@ -20,19 +21,42 @@ class CodeComment
...
+    # @param line [Integer] - start of the expression the comment belongs to
+    # @param source [String] - Path to source file or "string"
     #
-    def initialize(comment)
+    def initialize(comment:, line:, source:)
       @original_comment  = comment
       @config            = Hash.new { |hash, key| hash[key] = {} }
 
       @original_comment.scan(CONFIGURATION_REGEX) do |detector, _option_string, options|
+        unless Smells::SmellDetector.valid_detector?(detector)
```
Comment (mvz) [inline lib/reek/code_comment.rb]: Can we somehow avoid this dependency on a completely different part of the code? Perhaps we can move this check up the call stack a bit?

**Comment by troessner** [comment]
>> I'm leaning towards just aborting the examination of that file at the first error 

I like the sound of that, but aborting the examination of that file would require us to jump up **really** high on Examiner level again. And then catch this [here](https://github.com/troessner/reek/blob/master/lib/reek/cli/command/report_command.rb#L24) at ReportCommand and then again, at [TodoCommand](https://github.com/troessner/reek/blob/master/lib/reek/cli/command/todo_list_command.rb#L31). 
And in `ShouldReek#matches?` and so on.
So that won't work.
Or did you have something else in mind?

**Comment by mvz** [comment]
> Or did you have something else in mind?

I have in mind to handle it at the Examiner level. So [here](https://github.com/troessner/reek/blob/master/lib/reek/examiner.rb#L103) we would first catch `Reek::BadConfigurationError`, and then `StandardError`.

In `ShouldReek#matches?` it would just not be handled like all the other exceptions.

At a later stage, I'd like to extract all the exception handling in Examiner to a special handler object that we can pass to the Examiner at initialization, but that's a plan that still needs some simmering.

**Comment by troessner** [comment]
>> I have in mind to handle it at the Examiner level. So here we would first catch Reek::BadConfigurationError, and then StandardError.
In ShouldReek#matches? it would just not be handled like all the other exceptions.

Good idea! I'm going to look into this tomorrow :)

File: lib/reek/smells/smell_detector.rb [hunk 3]
```diff
@@ -105,6 +104,14 @@ def inherited(subclass)
         def descendants
           @descendants ||= []
         end
+
+        #
+        # @param detector [String] the detector in question, e.g. 'DuplicateMethodCall'
+        # @return [Boolean]
+        #
+        def valid_detector?(detector)
+          Reek::Smells.const_get(detector) rescue false
```
Comment (waldyr) [inline lib/reek/smells/smell_detector.rb]: Shouldn't we rescue only NameError?

Comment (backus) [inline lib/reek/smells/smell_detector.rb]: Could this just be `Reek::Smells.const_defined?(detector)`

File: lib/reek/code_comment.rb [hunk 4]
```diff
@@ -20,19 +21,42 @@ class CodeComment
     DISABLE_DETECTOR_CONFIGURATION = '{ enabled: false }'.freeze
     MINIMUM_CONTENT_LENGTH         = 2
     LEGACY_SEPARATOR               = ':'.freeze
+    UNKNOWN_SMELL_DETECTOR_MESSAGE = <<-EOS.freeze
```
Comment (backus) [inline lib/reek/code_comment.rb]: If you wrap `EOS` in single quotes then it will disable string interpolation FYI (equivalent to a string with single quotes)

File: lib/reek/code_comment.rb (hunk 1 above)
Comment (backus) [inline lib/reek/code_comment.rb]: I'm curious. Why you prefer `$stderr.puts` over `warn`?

File: lib/reek/code_comment.rb (hunk 4 above)
Comment (troessner) [inline lib/reek/code_comment.rb]: I don't follow -  why do you think wrapping EOS here makes sense?

File: lib/reek/code_comment.rb (hunk 1 above)
Comment (troessner) [inline lib/reek/code_comment.rb]: The only reason was for consistency reason since we use `stderr.puts` throughout Reek so far. But you're right, `warn` is more succinct and consistency in this case overrated, thanks for pointing that out!

File: lib/reek/code_comment.rb (hunk 2 above)
Comment (troessner) [inline lib/reek/code_comment.rb]: >> Can we somehow avoid this dependency on a completely different part of the code? 

Hmmm, but it's actually modelling what we do, isn't it? We create a comment here and this comment contains the description for a smell detector. So we let SmellDetector validate it right here. To me this seems like the responsibilities are distributed properly...

>> Perhaps we can move this check up the call stack a bit?

But then we would separate creation from validation. To me they belong together. Do you have an example for what you have in mind?

File: lib/reek/smells/smell_detector.rb (hunk 3 above)
Comment (troessner) [inline lib/reek/smells/smell_detector.rb]: Good point, let me look into this.

**Comment by troessner** [comment]
Ladies and gentlemen, after incorporating all of your comments this is ready for re-review!

File: lib/reek/code_comment.rb (hunk 2 above)
Comment (mvz) [inline lib/reek/code_comment.rb]: > But then we would separate creation from validation.

Yes, this would be an external validation. In general, I tend to avoid having internal validations if it creates too many dependencies.

However, it's probably best to go with this implementation for now, and then I can see if I can refactor it later and we can discuss this more then.

File: lib/reek/code_comment.rb [hunk 5]
```diff
@@ -25,14 +27,20 @@ class CodeComment
...
       @original_comment  = comment
       @config            = Hash.new { |hash, key| hash[key] = {} }
 
       @original_comment.scan(CONFIGURATION_REGEX) do |detector, _option_string, options|
+        unless Smells::SmellDetector.valid_detector?(detector)
+          raise BadDetectorInCommentError, detector: detector,
+                                           source: source,
+                                           line: line,
+                                           original_comment: @original_comment
+        end
```
Comment (mvz) [inline lib/reek/code_comment.rb]: I think @waldyr's check is further up in `SmellDetector`, but it would use the same mechanism.

File: lib/reek/smells/smell_detector.rb [hunk 6]
```diff
@@ -105,6 +104,14 @@ def inherited(subclass)
         def descendants
           @descendants ||= []
         end
+
+        #
+        # @param detector [String] the detector in question, e.g. 'DuplicateMethodCall'
+        # @return [Boolean]
+        #
+        def valid_detector?(detector)
+          Reek::Smells.const_defined?(detector)
```
Comment (mvz) [inline lib/reek/smells/smell_detector.rb]: This makes 'SmellWarning' a valid detector.

File: spec/reek/code_comment_spec.rb [hunk 7]
```diff
@@ -1,103 +1,129 @@
...
-      ').config
-      expect(config).to include('Duplication', 'NestedIterators')
-      expect(config['Duplication']).to include('enabled')
-      expect(config['Duplication']['enabled']).to be_falsey
-      expect(config['NestedIterators']).to include('enabled')
-      expect(config['NestedIterators']['enabled']).to be_truthy
+      EOF
+      comment = FactoryGirl.build(:code_comment, comment: original_comment)
+
+      expect(comment.config).to include('DuplicateMethodCall', 'NestedIterators')
```
Comment (mvz) [inline spec/reek/code_comment_spec.rb]: I'd prefer to avoid the duplicate `comment.config` here and in the other specs in this file by assigning to a local variable (as it was before).

File: lib/reek/context/module_context.rb [hunk 8]
```diff
@@ -64,7 +64,9 @@ def node_instance_methods
       end
 
       def descriptively_commented?
-        CodeComment.new(exp.leading_comment).descriptive?
+        CodeComment.new(comment: exp.leading_comment,
+                        line: exp.line,
+                        source: exp.source).descriptive?
```
Comment (troessner) [inline lib/reek/context/module_context.rb]: Ack.

File: lib/reek/smells/smell_detector.rb (hunk 6 above)
Comment (troessner) [inline lib/reek/smells/smell_detector.rb]: Good catch! Good thing we have `SmellDetector#descendants` :)

File: spec/reek/code_comment_spec.rb (hunk 7 above)
Comment (troessner) [inline spec/reek/code_comment_spec.rb]: Fair enough, updated.

File: lib/reek/code_comment.rb (hunk 4 above)
Comment (backus) [inline lib/reek/code_comment.rb]: I was just pointing out helpful syntax that I think many people aren't aware of. Basically you can write something like

```ruby
<<-ANY_HEREDOC
foo
bar
baz
ANY_HEREDOC
```

with single quotes wrapping the heredoc end of string token like so

```ruby
<<-'ANY_HEREDOC'
foo
bar
baz
ANY_HEREDOC
```

the benefit of this is that it signals that interpolation doesn't happen in the entire heredoc

Comment (troessner) [inline lib/reek/code_comment.rb]: Fair enough - thanks for the tip! I was indeed not aware of this ;)
I'll keep this in mind for the future. If we introduce this syntax into Reek we probably should update all heredocs to be consistent from the start, which would warrant its own PR.

Comment (backus) [inline lib/reek/code_comment.rb]: Fair enough

**Comment by troessner** [comment]
Addressed all comments! LGTM? :)

**Comment by troessner** [comment]
Pinging @mvz - sorry for being pushy but I'd like to continue with checking the config hash itself which will be build on top of this PR..

**Comment by mvz** [comment]
@troessner no problem, this one slipped under the radar today. Looks good, merging!

**Comment by troessner** [comment]
And I just released 4.4.2 with those changes!
Another small step to a Reek that is more resilient to bad input :)
